### ISSUE TITLE
gulp-useref deep folders error

### ISSUE THREAD

**Issue by huanxijiuhao** [jonkemp/gulp-useref#209]
While execute gulp task with gulp-useref with deep folders, throw Error. But if i delete test folder, no error happend. Is anybody has any ideas?
<pre><code>throw new Error('Invalid glob argument:' + glob);
Error: Invalid glob argument:
    at Object.src(.....\node_modules\gulp-useref\node_modules\vinyl-fs\lib\src\index.js:32:11)
    at D:\Project\community\auto-community\src\main\webapp\WEB-INF\public\node_modules\gulp-useref\lib\streamManager.js:142:47
    at Array.forEach (native)
</code></pre>
>My situation
<pre><code>project directory
Project
  --app
      --html
         --a.html
         --test
            --b.html
      --css
      --js
  --dist
     --html
     --js
     --css
</code></pre>
> code
<pre><code>var gulp = require('gulp');
var useref = require('gulp-useref');
var cssnano = require('gulp-cssnano');
var uglify = require('gulp-uglify');
var gulpIf = require('gulp-if');
gulp.task('default', function(){
	return gulp.src('app/**/*.html')
		.pipe(useref())
		.pipe(gulpIf('*.js', uglify()))
		.pipe(gulpIf('*.css', cssnano()))
		.pipe(gulp.dest('dist'))
});
</code></pre>

**Comment by huanxijiuhao** [comment]
Sorry, I have solved this problem. 
The reason of this error is that I add a script which src attribute is from http in  task.
