### ISSUE TITLE
Get scripts and stylesheets from remote locations via http

### ISSUE THREAD

**Issue by mattbrunetti** [jonkemp/gulp-useref#223]
Get scripts and stylesheets from remote locations via http, not just from the local file system

I think this would be awesome. We could easily drop in resources from CDNs or raw.githubusercontent.com or private servers. Some small projects might not even need a package manager.

@jonkemp Is this a feature you're interested in supporting? Would you review a PR?

btw, I tried doing this and this is the error I got, so I'm just assuming it's not supported..
```
C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\node_modules\vinyl-fs\lib\src\index.js:32
    throw new Error('Invalid glob argument: ' + glob);
    ^

Error: Invalid glob argument: 
    at Object.src (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\node_modules\vinyl-fs\lib\src\index.js:32:11)
    at DestroyableTransform.addAssetsToStream (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\index.js:60:15)
    at C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\index.js:119:31
    at Array.forEach (native)
    at DestroyableTransform.processAssets (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\index.js:110:11)
    at C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\gulp-useref\index.js:172:31
    at Stream.<anonymous> (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\event-stream\index.js:306:20)
    at _end (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\mbrunetti\Documents\mtdirect-frontend\node_modules\readable-stream\lib\_stream_readable.js:504:10)

Process finished with exit code 1
```

**Comment by jonkemp** [comment]
Not really interested. Thanks.

**Comment by mattbrunetti** [comment]
Ok. That's cool. Thanks.
