### ISSUE TITLE
useref choking for unknown reason

### ISSUE THREAD

**Issue by thejohnfreeman** [jonkemp/gulp-useref#39]
I've got useref in my gulp pipeline:

```js
  return gulp.src(['*.html', 'templates/*'], {cwd: 'www', base: 'www'})
    .pipe(useref.assets())
    .pipe(useref.restore())
    .pipe(useref())
    .pipe(gulp.dest('dist'))
```

Even with an index.html that has no useref directives in it, I get this error now:

```
/.../node_modules/gulp-useref/index.js:40
        var output = useref(file.contents.toString());
                                          ^
TypeError: Cannot call method 'toString' of null
    at Transform._transform (/.../node_modules/gulp-useref/index.js:40:43)
    at Transform._read (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
    at clearBuffer (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:317:5)
    at onwrite (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:275:7)
    at WritableState.onwrite (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:107:5)
    at afterTransform (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at afterWrite (/.../node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:290:3)

**Comment by jonkemp** [comment]
Is this still an issue? If so, could you update the title?

**Comment by thejohnfreeman** [comment]
I haven't been working on JavaScript projects lately, so I don't care to check if it's still an issue. I'll close this for now and re-open if I run into it again.
