### ISSUE TITLE
TypeError: Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by salttis** [jonkemp/gulp-useref#44]
Hey!

I'm experiencing a weird error with my project and I suspect it's coming from gulp-useref.
My gulpfile used to work without errors, but after I updated, it doesn't work.

Error:

``` sh
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.EventEmitter.emit (events.js:74:15)
    at Transform.onerror (/Users/***/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:540:12)
    at Transform.EventEmitter.emit (events.js:95:17)
    at Transform.<anonymous> (/Users/***/node_modules/gulp-useref/index.js:80:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/***/node_modules/gulp-useref/index.js:68:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/***/node_modules/gulp-useref/index.js:46:36)
    at Array.forEach (native)
```

Gulpfile.js:

``` js
gulp.task('html', ['html:clean'], function(){
  var jsFilter  = filter('**/*.js')
    , cssFilter = filter('**/*.css')
    , htmlFilter = filter('**/*.html');

  return gulp.src([Config.paths.app.root + '/*.html', '!./app/lib/**'])
    .pipe(useref.assets())
    .pipe(jsFilter)
    .pipe(uglify())
    .pipe(jsFilter.restore())
    .pipe(cssFilter)
    .pipe(minifyCss())
    .pipe(cssFilter.restore())
    .pipe(useref.restore())
    .pipe(useref())
    .pipe(htmlFilter)
    .pipe(minifyHtml({ quotes: true, conditionals: true }))
    .pipe(htmlFilter.restore())
    .pipe(gulp.dest(Config.paths.dist.root));
})
```

Versions:

``` sh
├─┬ gulp-useref@0.5.0
│ ├─┬ glob@4.0.4
│ │ ├── graceful-fs@3.0.2
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@0.3.0
│ │ │ ├── lru-cache@2.5.0
│ │ │ └── sigmund@1.0.0
│ │ └── once@1.3.0
│ ├─┬ gulp-util@2.2.20
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├── escape-string-regexp@1.0.1
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├─┬ strip-ansi@0.3.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └── supports-color@0.2.0
│ │ ├── dateformat@1.0.8-1.2.3
│ │ ├── lodash._reinterpolate@2.4.1
│ │ ├─┬ lodash.template@2.4.1
│ │ │ ├── lodash._escapestringchar@2.4.1
│ │ │ ├─┬ lodash.defaults@2.4.1
│ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ ├─┬ lodash.escape@2.4.1
│ │ │ │ ├─┬ lodash._escapehtmlchar@2.4.1
│ │ │ │ │ └── lodash._htmlescapes@2.4.1
│ │ │ │ └─┬ lodash._reunescapedhtml@2.4.1
│ │ │ │   └── lodash._htmlescapes@2.4.1
│ │ │ ├─┬ lodash.keys@2.4.1
│ │ │ │ ├── lodash._isnative@2.4.1
│ │ │ │ ├─┬ lodash._shimkeys@2.4.1
│ │ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ │ └─┬ lodash.isobject@2.4.1
│ │ │ │   └── lodash._objecttypes@2.4.1
│ │ │ ├── lodash.templatesettings@2.4.1
│ │ │ └── lodash.values@2.4.1
│ │ ├─┬ multipipe@0.1.1
│ │ │ └─┬ duplexer2@0.0.2
│ │ │   └─┬ readable-stream@1.1.13-1
│ │ │     ├── core-util-is@1.0.1
│ │ │     ├── inherits@2.0.1
│ │ │     ├── isarray@0.0.1
│ │ │     └── string_decoder@0.10.25-1
│ │ └─┬ vinyl@0.2.3
│ │   └── clone-stats@0.0.1
│ ├── is-absolute-url@0.1.0
│ ├── node-useref@0.3.2
│ ├─┬ strip-bom@0.3.1
│ │ ├── first-chunk-stream@0.1.0
│ │ └── is-utf8@0.2.0
│ └─┬ through2@0.5.1
│   ├─┬ readable-stream@1.0.27-1
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.25-1
│   └── xtend@3.0.0
```

**Comment by thepuzzlemaster** [comment]
After a long struggle with this issue, we ended up realizing that on our project, the gulp-minify-css package had bumped up to v0.3.12 which broke things, while v0.3.11 worked.

In case it helps anyone else...

**Comment by silvenon** [comment]
Newer versions of gulp-useref report which file(s) could not be found, which should help a great deal with debugging.

**Comment by Stichoza** [comment]
Thanks @thepuzzlemaster! I had the same issue as you and your comment about `gulp-minify-css` helped me. I don't know what happens in `v0.3.11`, but it's broken as I see.

**Comment by jonathanepollack** [comment]
@thepuzzlemaster can you run `npm update` and tell me if you still have issues with [gulp-minify-css#61](https://github.com/jonathanepollack/gulp-minify-css/issues/61)?

**Comment by thepuzzlemaster** [comment]
@jonathanepollack 
I updated to v0.4.2, and I get the same error: 

````
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DestroyableTransform.emit (events.js:74:15)
    at DestroyableTransform.onerror (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:95:17)
    at onwriteError (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/ilan.epstein/Projects/korn-ferry/component-lib/node_modules/build-system/node_modules/gulp-minify-css/index.js:113:9
````

Downgrading back to v0.3.11 fixes the issue. Let me know if you need any other info.

**Comment by jonathanepollack** [comment]
Can you delete you `node_modules/` folder, and do an `npm install`?

**Comment by thepuzzlemaster** [comment]
@jonathanepollack assuming that was directed at me, I ran `rm -rf node_modules`  `npm cache clean` `npm install` `npm list --depth=0` to verify that v0.4.2 was installed, and then `gulp`. Still getting the same error unfortunately.

**Comment by jonathanepollack** [comment]
@thepuzzlemaster -- it was, and lets take this to [gulp-minify-css#61](https://github.com/jonathanepollack/gulp-minify-css/issues/61). I would love to solve your problem.

**Comment by Artsu** [comment]
I was missing dist folder from bower_components' jquery due to messing up things by myself. The error "events.js:74 throw TypeError('Uncaught, unspecified "error" event.');" was not very informative so I struggled a bit finding out the real reason behind this error. Managed to catch the real culprit by adding the following:

```js
    var gutil = require('gulp-load-utils')(['log']);

    return gulp.src('client/*.html')
               .pipe($.useref.assets().on('error', gutil.log))
               .pipe($.useref.restore())
               .pipe($.useref())
```

gulp-load-utils requires the following:
```
    "gulp-load-utils": "0.0.4",
    "chalk": "^0.5.1",
    "dateformat": "^1.0.11",    
```

->
```
[gulp] [15:53:13] gulp-useref: no such file or directory '/Users/arimattin/Workspaces/SuggestMe/client/bower_components/jquery/dist/jquery.js'
```

Hope this helps someone who bumps into the same error.

**Comment by silvenon** [comment]
Are you sure you were using the latest gulp-useref? I think it should've output a more informative error message, i.e. which file was missing.

**Comment by Artsu** [comment]
Ah, actually I had some older (read: ancient) version installed. Didn't even bother to check since this issue had some pretty recent comments, my bad! :-)

Tried with the latest version and interestingly enough it just continued happily even though I tried removing the same dist folder to check on the error logging.

**Comment by Lbatson** [comment]
@Artsu your fix worked for me to figure out what was wrong. the original error message from useref was very cryptic until using gulp-utils log. thanks :+1:

**Comment by sergeybochkarev** [comment]
http://www.widecodes.com/0SiVePjPkk/socketrocket-crashes-nodejs-websocket.html

wss.on('connection', function(connection) {
  connection.on('error', function(reason, code) {
    console.log('socket error: reason ' + reason + ', code ' + code);
  });
}

**Comment by thedevsaddam** [comment]
I have the same problem. How can I fix it?
